version: '3.8'
name: api-tibia-info
services:
  db:
    container_name: db-tibia-info
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=db-tibia-info
